#!/usr/bin/env python3
##  /\__/\
#  (=^ .^=)
#   (")(")__/  
##
# Script Name:             Ops Challenge 31
# Author:                  Kimberly Dills
# Date of last revision:   11/16/2020
# Description of purpose:  Signature-based Malware Detection
# Event Logging Tool Part: 1 of 3
# 
import os
import glob

# variable
# Prompt the user to type the file name to search for

fileName = input("What file are you searching for? ")

# Prompt the user for what directory to search in

dirName = input("What directory is the file in? ")
print("Please wait for your response.")

# Function 
# Search each file in the directory by name

for file in os.listdir('C:\\home\osboxes\Desktop\\'+ dirName):
    print(os.path.join(dirName, file))

# For each positive detection, print file name and location
print(fileName, dirName)

# Print how many files were searched and how many hits were found

path = r'C:\\home\osboxes\Desktop\\'
count = 0
l = os.listdir(path)
print(l)
count += 1
print(count)
g = glob.glob('*.py')
print(g)

# if comment out

#path = r'C:\\home\osboxes\Desktop
#count = 0
#l = os.listdir(path)
#print(l)
#g = glob.glob('*.py')
#print(g)
