#!/usr/bin/env python3
##  /\__/\
#  (=^ .^=)
#   (")(")__/  
##
# Script:                 Ops 401 16
# Author:                 Kimberly Dills
# Date of last revision:  10/26/2020
# Description of purpose: Automated Brute Force Wordlist Attack Tool 1 of 3

# Import Libraries 
import os
import itertools
import time
# import pyautogui

def user_selection():
    user_choice=input("""
    select a mode:
    1. Mode 1
    2. Mode 2
    3. Exit
    """)

    if(user_choice =="1"):
        mode1()
    elif(user_choice =="2"):
        mode2
    else: 
        print("Exit")
        exit()

# Mode 1 
def mode1():

# Accept a user input word list file path and iterates through the word lisst assinging the word being read to a variable
  word_list = input("Enter a Filename: ")
#textfile=os.path.abspath(word_list)
  filename=open(word_list, "r", encoding= "ISO-8859-1")
  filename=filename.readlines()

  for line in fileline:
    print(line)
# Adding a delay between words sleep for 2 seconds
    time.sleep(2)

# stop the run

# Mode 2
def mode2():

# Accepts a user input string
  user_string=input("Enter a String: ")
# Accepts a user input word list file path
  word_list = input("Enter a Filename: ")
  filename=open(word_list, "r", encoding= "ISO-8859-1")
  fileline=filename.read().splitlines()
# Search the word list for the user input string
  if str(line) == user_string:
      print("There was a match")
  break
  else:  
      print("No match was found")
input()
     

# Print to the screen wheather the string appeared in the word list

user_selection()

# End
