#!/usr/bin/env python3
##  /\__/\
#  (=^ .^=)
#   (")(")__/  
##
# Script:                 Ops 401 11
# Author:                 Kimberly Dills
# Date of last revision:  10/18/2020
# Description of purpose: Network Security Tool with Scapy 1 of 3
import sys
import socket
import random
import scapy
from scapy.all import sr1,IP,ICMP,TCP

host = "scanme.nmap.org"
port_range = [21, 22, 23]
src_port = 22
dst_port = 22
###Function###
for dst_port in port_range:
    src_port = random.randint(1025,65534)
    response = sr1(IP(dst=host)/TCP(sport=src_port,dport=dst_port,flags="S"),timeout=1,verbose=0)
    if response is None:
        print("packet filtered")
    elif(response.haslayer(TCP)):
        if(response.getlayer(TCP).flags == 0x12): #port responding and open
            print("Port" + str(dst_port)+" is open")
        elif (response.getlayer(TCP).flag == 0x14):
            print("Port" + str(dst_port)+"T is closed")
        else:
            print("The port is filtered and dropped”)
# Main
# resources:
#sea-d44-front-end
