#!/usr/bin/env python3

#!/usr/bin/env python3
##  /\__/\
#  (=^ .^=)
#   (")(")__/  
##
# Script:                 Ops 401 02
# Author:                 Kimberly Dills
# Date of last revision:  10/6/2020
# Description of purpose: Uptime Sensor Tool
##

import os, time, datetime

def check_ping(target):

    response = os.system("ping -c 1 " + target)
     
    # and then check the response
    if response ==0:
        pingstatus = "Network Active"
    else:
        pingstatus = "Network Error"

    return pingstatus
# Handle function output

pingstatus = check_ping("8.8.8.8")

# Infinite Heartbeat

while True:
    now = datetime.datetime.now()
    print(str(now) + " " + pingstatus + " to 8.8.8.8")
    time.sleep(2)

# End
    

