#!/usr/bin/python3
##  /\__/\
#  (=^ .^=)
#   (")(")__/  
##
# Script:                 Ops 401 45
# Author:                 Kimberly Dills
# Date of last revision:  12/8/20
# Description of purpose: Creating a Banner Grabber

import socket

def bannergrab(host, port):
    timeout = 8
    sockmod = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sockmod.connect((host, int(port)))
    sockmod.settimeout(timeout)
    print(sockmod.recv(1024))

def main():
    host = input("What Ip do you want to grab banner? ")
    port = input("What port you want to grab banner? ")
    bannergrab(host, port)

main()
