#! /usr/bin/env python3
##  /\__/\
#  (=^ .^=)
#   (")(")__/  
##
# Script:                 Ops 401 37
# Author:                 Kimberly Dills
# Date of last revision:  11/24/2020
# Description of purpose: Cookie Capture

# The below Python script shows one possible method to return the cookie from a site that supports cookies.

import requests
import os

# targetsite = input("Enter target site:") # Uncomment this to accept user input target site
targetsite = "http://www.whatarecookies.com/cookietest.asp" # Comment this out if you're using the line above
response = requests.get(targetsite)
cookie = response.cookies

def bringforthcookiemonster(): # Because why not!
    print('''

              .---. .---.
             :     : o   :    me want cookie!
         _..-:   o :     :-.._    /
     .-''  '  `---' `---' "   ``-.
   .'   "   '  "  .    "  . '  "  `.
  :   '.---.,,.,...,.,.,.,..---.  ' ;
  `. " `.                     .' " .'
   `.  '`.                   .' ' .'
    `.    `-._           _.-' "  .'  .----.
      `. "    '"--...--"'  . ' .'  .'  o   `.

        ''')

bringforthcookiemonster()
print("Target site is " + targetsite)
print(cookie)

#####Add here some code to make this script perform the following:

# Send the cookie back to the site and receive a HTTP response
cookiemonsterhtml = requests.get(targetsite, cookies=cookie)
website = cookiemonsterhtml.text

# Generate a .html file to capture the contents of the HTTP response
with open ('cookiemonster.html', 'w') as file:file.write(website)

# Print to screen that website is opening
print("Please wait, baking cookies...")

# Open it with Firefox
os.system("firefox /home/osboxes/cookiemonster.html")

# End
