#!/usr/bin/python3
##  /\__/\
#  (=^ .^=)
#   (")(")__/  
##
# Script:                 Ops 401 44
# Author:                 Kimberly Dills
# Date of last revision:  12/7/20
# Description of purpose: Create a Port Scanner

import os
import socket

sockmod = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
timeout = 3000
sockmod.settimeout(timeout)

hostip = input("What Ip address? ")
portno = input("What Port? ")

def portScanner(portno):
    if sockmod.bing((hostip, int(portno))): \
        print("Port closed")
    else:
        print("Port open")

portScanner(port)


